horizon: filter out X-Forwarded-* and EDNS0_SUBNET when forwarding isn't allowed
darvaza-proxy/penne pull request #20
Opened 2024-01-05 17:40 UTC by amery

and inject a new EDNS0_SUBNET based on the Horizon.Match

We probably want to add a flag on iterative and forwarder resolvers to remove it before connecting to the remote servers.

2024-01-05 23:23 UTC, amery commented
fixed typo. option to remove EDNS0_SUBNET available as PR after https://github.com/darvaza-proxy/resolver/pull/74

2024-01-06 12:33 UTC, karasz commented on pkg/horizon/http.go
> +}
you may want to add `Forwarded` which is defined in rfc7239

2024-01-06 12:33 UTC, karasz requested changes
LGTM

2024-01-06 16:31 UTC, amery commented
added `Forwarded` as requested, but also extended to include EDNS0_SUBNET when forwarding is allowed but the field isn't already included

2024-01-06 16:33 UTC, amery commented
update darvaza.org/resolver as the last commit uses exdns.ForEachRR()

2024-01-06 19:21 UTC, amery commented
rebased and added the commit that implements OmitSubNet on the iterative resolver

2024-01-06 21:40 UTC, karasz approved these changes

2024-01-06 21:40 UTC, merged