resolver: add comments to `Config` fields, and clean redundant yaml annotations
darvaza-proxy/penne pull request #24
Opened 2024-01-10 16:25 UTC by amery

2024-01-10 17:44 UTC, karasz requested changes
LGTM maybe with some caveats? see comments

2024-01-10 17:44 UTC, karasz commented on pkg/resolver/config.go
> +	// Iterative indicates this [Resolver] will go straight to the roots and
Iterative indicates this *that* [Resolver] will go straight to the DNS root servers and

2024-01-10 17:44 UTC, karasz commented on pkg/resolver/config.go
> +	// Recursive indicates this [Resolver] will ask servers to perform recursive lookups.
same as above

2024-01-10 17:44 UTC, karasz commented on pkg/resolver/config.go
> +	// a built-in list of root servers will be used.
a built-in list of root DNS servers will be used.

2024-01-10 17:48 UTC, karasz commented on pkg/resolver/config.go
> +	// Iterative indicates this [Resolver] will go straight to the roots and
> Iterative indicates this _that_ [Resolver] will go straight to the DNS root servers and

*that this*, sorry

2024-01-10 17:52 UTC, amery commented
amended, please re-check @karasz

2024-01-11 09:08 UTC, karasz approved these changes
LGTM

2024-01-11 09:08 UTC, merged